### ISSUE TITLE
【要望】タイルサイズやコマ数を自由に指定できるようにしてほしいです

### ISSUE THREAD

**Issue by makottyan** [jiro4989/TKoolFacetileMaker2#58]
初めまして。始めてIssueを書くので失礼なことをしてしまっていたらごめんなさい。

## 要望
タイルサイズやコマ数を自由に指定できるようにしてほしいです

### 詳細
現在はRPGツクールMV，VXAceサイズのみですが、例えば一コマ200*200などのサイズで横5列、縦3列などのようにカスタムできるようにしてほしいです。
ソースコードをちょっと覗いたのですが、CropSize.javaのように切り抜きサイズを指定できると助かります。
多分ソースコードをDLしていじってビルド？すればできるのでしょうが、javaの知識がないためエディタ上またはコンフィグファイルで指定できるようになると助かります。
Jiro様の別ツール　TKoolImageTileEditor　では画像サイズプリセットが作成できるので、そのような感じにしていただけると助かります！

## 理由
以前RPGツクールMVでゲーム制作をしていた際にこちらを利用していました。とても便利で感謝しています。
現在別エンジンでゲーム制作をしているのですが、なかなかこのような簡単に立ち絵の表情差分をまとめた画像を作るツールが見つからず、Jiro様に対応してほしくIssueを書きました。
このツールは本当に便利で感謝しています。ゲーム制作の時だけでなく、差分をまとめて並べるのにはこのツールが一番と言っていいほど使いやすいです。

よろしくお願いします！

**Comment by jiro4989** [comment]
要望ありがとうございます。

なるほど、あると便利そうな機能ですね。

もはやツール名にもあるツクールの域を超えてしまいますが、
汎用的に使えることは良いことなので、検討してみます。

**Comment by jiro4989** [comment]
できるようにしてみました

![image](https://user-images.githubusercontent.com/13825004/147384590-52f09f2e-ca23-4c74-accb-d48a6054e5a9.png)

v3.5.0 をダウンロードして試してみてください

https://github.com/jiro4989/TKoolFacetileMaker2/releases

**Comment by jiro4989** [comment]
使い方はここに書きました

https://github.com/jiro4989/TKoolFacetileMaker2/tree/v3.5.0#%E3%83%A6%E3%83%BC%E3%82%B6%E7%8B%AC%E8%87%AA%E3%81%AE%E7%94%BB%E5%83%8F%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88%E3%81%AE%E8%BF%BD%E5%8A%A0

**Comment by makottyan** [comment]
確認しました！
概ね希望通りの操作なのですが、画像切り取りサイズが大きい（500*1000など）場合拡大縮小などを行うUIが埋もれて非表示になってしまいますね。
お手数おかけしますが、確認していただけたら幸いです。
![image](https://user-images.githubusercontent.com/35626697/147564437-130b0b66-44d3-448c-903f-04961843dccd.png)

**Comment by jiro4989** [comment]
なるほど、そういうケースがあるんですねちょっと考えてみます

**Comment by jiro4989** [comment]
実際のところそういう操作をするケースを想定してますか？
元々このツールは名前の通り表情差分をまとめるツールなので、大きなタイルを作ることを想定したUIにしていません

**Comment by jiro4989** [comment]
単純に気になった程度での報告なのでしたら、別に直すつもりはありません。

実際にそういう使い方を考えているのでしたら、対応を検討します

**Comment by makottyan** [comment]
返信遅くなり申し訳ございません。
ゲームでの利用以外に、立ち絵の表情差分に加えポーズ差分をまとめて一枚に出力し、原寸大の立ち絵と並べてキャラクターシートとして利用することも想定しているので、できたら大きなサイズに対応していただけたら嬉しいです。
少なくともこちらが確認した限りでは、200*400でもフルスクリーンにしないと拡大縮小などを行うバーが表示されません。また、出力画像プレビューも原寸なので若干見にくくなってしまいます。
こちらの環境は1920*1080の一般的なモニターです。設定は200*400で3列1行です
フルスクリーン時　![image](https://user-images.githubusercontent.com/35626697/147723446-71972a28-9a08-40f0-8a0a-1ce2e9c71d54.png)
縮小時　
![image](https://user-images.githubusercontent.com/35626697/147723492-bb74337a-39c0-44ba-b390-579f85320922.png)
また、切り抜き位置を動かした際に灰色の枠が軌跡に沿って残ってしまうのも確認しました。
お手数おかけしますが、

1. 拡大縮小などを行うバーの固定
2. 出力画像プレビューの拡大縮小
3. 切り抜き位置を動かした際に生まれる灰色の枠

を対応していただけたら嬉しいです。
わがままで申し訳ございません。よろしくおねがいします。

**Comment by jiro4989** [comment]
拡縮のバーと出力画像プレビューについては検討します。

灰色の枠が残るのは既知の問題ですが、出力する画像には影響しないので無視しています。よって対応しません

**Comment by makottyan** [comment]
ありがとうございます。
灰色の枠についても了解いたしました！　検討よろしくおねがいします。

**Comment by jiro4989** [comment]
大きいサイズのトリミングをしようとしてもUIが崩れないようにしました。

> 拡大縮小などを行うバーの固定

については解消したはずです。

![image](https://user-images.githubusercontent.com/13825004/147874754-732b85db-ad2d-4830-855e-63b053b921c9.png)

> 出力画像プレビューの拡大縮小

拡縮はできないですが、出力画像プレビューの領域をマウスドラッグで変更できる上限値を上げました。

「出力画像プレビュー」という文字の上の横棒の部分をマウスで操作すると高さを調整できます。
コレ自体は以前からできていたのですが、上限を上げました。

出力画像プレビューの領域を広くできるので、それで課題が解決するか試してもらえますか。

出力画像の拡縮調整出来るようにするのは適当なUIを決めるのが難しく、あんまりやりたくないです。
出力画像プレビューの領域を可変にしたことで事象が解決するのであれば、それで終わりとしたいです

v3.7.0を使ってもらえると

https://github.com/jiro4989/TKoolFacetileMaker2/releases

**Comment by makottyan** [comment]
ご対応ありがとうございます！
確認しました！
こちらの課題については解消いたしました！　要望に応えていただきありがとうございます！
出力画像プレビューについても了解いたしました。現状の仕様で私は十分だと思います！

この度は要望に応えてくださり本当にありがとうございました！
最初の要望とは別に追加の要望を出してしまって申し訳ございません。最終的にすべて応えていただいて、本当にありがとうございます！
これでゲーム制作が捗ります！　次郎様の制作活動をこれからも応援しております！
